### ISSUE TITLE
[FEATURE] Tag project

### ISSUE THREAD

**Issue by SpareSimian** [AvyAddons/BetterBags_Bound#1]
I suggest tagging the project to make it easy to find by BB users. I'm using the tag wow-betterbags-plugin. Click the gear icon to the right of the main project page to bring up project settings and add tags. (I'm open to using a different tag.)

https://github.com/topics/wow-betterbags-plugin

**Comment by lucasvienna** [comment]
Sounds good! I've tagged my BB projects with the suggested topic
