### ISSUE TITLE
[FEATURE] Compatibility with "BetterBags - Priority"

### ISSUE THREAD

**Issue by Levinaxr** [AvyAddons/BetterBags_Bound#3]
REQUEST: Add compatibility with "BetterBags - Priority" extension addon.

Would be great to be able to adjust the priority filtering of your addon with others. Mainly it'd be great to ensure that your BoEs take priority over "BetterBags - iLvl"s filtering, so one can easily sort out low level transmog junk but still easily be able to spot potentially worthwhile BoEs to trade without having to search around.
The Priority addon features a simple guide in how to be implemented in its own description.

**Comment by lucasvienna** [comment]
I'm looking into it, seems simple enough

**Comment by lucasvienna** [comment]
Done, check v1.5.0 once it hits Curse or Wago!
