### ISSUE TITLE
[FEATURE] Soulbound category

### ISSUE THREAD

**Issue by ZehelFenris** [AvyAddons/BetterBags_Bound#5]
### Is your feature request related to a problem?
I'm using the BetterBags default category that sorts things into types instead of having a single group for everything from an expansion but it splits equipment into multiple groups such as Armor, Weapon and Jewellery where I would like them all to be in a single group.

### What solution would you like?
Add Soulbound as a category

### What alternatives have you considered?
Turning the Type category off and having to install another plugin to add the sorting that Type does but without the equipment being split up, but I would rather not add yet another plugin to my already too many plugins that may conflict with each other

**Comment by lucasvienna** [comment]
I can add the Soulbound category, sure. It would be disabled by default and would work best with the "Only Equippable" toggle turned on, however!
![image](https://github.com/user-attachments/assets/0b6f4dc7-7303-4f84-8a91-f8890ff38f71)

**Comment by lucasvienna** [comment]
Added in v1.6.0!
